language: vba
install:
  - composer install
  - cp -r vendor/beakerboy/vba_tokenizer/src/Standards/VBA vendor/squizlabs/php_codesniffer/src/Standards/
script:
  - vendor/bin/phpcs --extensions=cls/vba,bas/vba --standard=VBA $TRAVIS_BUILD_DIR/src
after_success:
  - sudo apt-get install -qq mono-complete
  - wget https://www.naturaldocs.org/download/natural_docs/2.0.2/Natural_Docs_2.0.2.zip -O /tmp/ND.zip
  - unzip /tmp/ND.zip -d /tmp
  - mkdir $TRAVIS_BUILD_DIR/docs
  - mkdir $TRAVIS_BUILD_DIR/.ND_Config
  - cp .nd_project.txt $TRAVIS_BUILD_DIR/.ND_Config/Project.txt
  - mono /tmp/Natural\ Docs/NaturalDocs.exe $TRAVIS_BUILD_DIR/.ND_Config
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: $TRAVIS_BUILD_DIR/docs
  github_token: $GH_REPO_TOKEN
  on:
    branch: master
