VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "iSQLRecordset"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
Public Sub OpenRecordset(MyQuery As String, Connection)

End Sub

Public Sub CloseRecordset()

End Sub

Public Function GetValue(MyFieldname)

End Function

Public Function State()

End Function
