VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "iSQLConnection"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
Public Sub OpenConnection()

End Sub

Public Sub CloseConnection()

End Sub

Public Property Let ConnectionString(sConnection As String)

End Property

Public Function State()

End Function
