VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "iSQLQuery"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True

' Interface: iSQLQuery
' A common interface for the different query types

' Function: toString
' Convert the object to a string
Public Function toString() As String

End Function
