VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "SQLCreate"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit
Implements iSQLQuery

Public Function iSQLQuery_ToString() As String
    Dim return_string As String
    iSQLQuery_ToString = return_string
End Function
