VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "SQLTestConnection"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Implements iSQLConnection

Public Property Get iSQLConnection_Connection()
  
End Property

Public Sub iSQLConnection_OpenConnection()

End Sub

Public Sub iSQLConnection_CloseConnection()

End Sub

Public Function iSQLConnection_State()

End Function

Public Property Let iSQLConnection_ConnectionString(sConnection As String)

End Property
